version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: res
      POSTGRES_USER: res
      POSTGRES_PASSWORD: res
networks:
  default:
    external:
      name: res_food_v2_default